SSE_FUNDS_SCHEDULE="0 9 * * 1"
SSE_DETAILS_SCHEDULE="0 16 * * 1-5"
SZSE_FUNDS_SCHEDULE="0 9 * * 1"
SZSE_DETAILS_SCHEDULE="0 22 * * 1-5"
CSRC_FUNDS_SCHEDULE="0 9 1 * *"
CSRC_DETAILS_SCHEDULE="0 22 * * 1-5"
