"""separate index families and add master data provenance

Revision ID: b442c1f4367d
Revises: f421173b98a0
Create Date: 2026-08-13 00:53:42.423440
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b442c1f4367d'
down_revision: Union[str, None] = 'f421173b98a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('index_family',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_index_family_quality_status'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('fund_listing', sa.Column('source_document_id', sa.BigInteger(), nullable=True))
    op.add_column('fund_listing', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('fund_listing', sa.Column('source_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_listing', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_listing', sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fund_listing', sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False))
    op.create_foreign_key('fk_fund_listing_source_document', 'fund_listing', 'source_document', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.add_column('fund_product', sa.Column('canonical_code', sa.String(length=120), nullable=False))
    op.add_column('fund_product', sa.Column('source_document_id', sa.BigInteger(), nullable=True))
    op.add_column('fund_product', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('fund_product', sa.Column('source_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_product', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_product', sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fund_product', sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False))
    op.create_unique_constraint('uq_fund_product_canonical_code', 'fund_product', ['canonical_code'])
    op.create_foreign_key('fk_fund_product_source_document', 'fund_product', 'source_document', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.add_column('fund_share_class', sa.Column('source_document_id', sa.BigInteger(), nullable=True))
    op.add_column('fund_share_class', sa.Column('source_url', sa.Text(), nullable=True))
    op.add_column('fund_share_class', sa.Column('source_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_share_class', sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('fund_share_class', sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('fund_share_class', sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False))
    op.create_foreign_key('fk_fund_share_class_source_document', 'fund_share_class', 'source_document', ['source_document_id'], ['id'], ondelete='SET NULL')
    op.add_column('index_definition', sa.Column('family_id', sa.String(length=64), nullable=False))
    op.create_index('ix_index_definition_family', 'index_definition', ['family_id'], unique=False)
    op.create_foreign_key('fk_index_definition_family', 'index_definition', 'index_family', ['family_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_index_definition_family', 'index_definition', type_='foreignkey')
    op.drop_index('ix_index_definition_family', table_name='index_definition')
    op.drop_column('index_definition', 'family_id')
    op.drop_constraint('fk_fund_share_class_source_document', 'fund_share_class', type_='foreignkey')
    op.drop_column('fund_share_class', 'quality_status')
    op.drop_column('fund_share_class', 'collected_at')
    op.drop_column('fund_share_class', 'effective_from')
    op.drop_column('fund_share_class', 'source_time')
    op.drop_column('fund_share_class', 'source_url')
    op.drop_column('fund_share_class', 'source_document_id')
    op.drop_constraint('fk_fund_product_source_document', 'fund_product', type_='foreignkey')
    op.drop_constraint('uq_fund_product_canonical_code', 'fund_product', type_='unique')
    op.drop_column('fund_product', 'quality_status')
    op.drop_column('fund_product', 'collected_at')
    op.drop_column('fund_product', 'effective_from')
    op.drop_column('fund_product', 'source_time')
    op.drop_column('fund_product', 'source_url')
    op.drop_column('fund_product', 'source_document_id')
    op.drop_column('fund_product', 'canonical_code')
    op.drop_constraint('fk_fund_listing_source_document', 'fund_listing', type_='foreignkey')
    op.drop_column('fund_listing', 'quality_status')
    op.drop_column('fund_listing', 'collected_at')
    op.drop_column('fund_listing', 'effective_from')
    op.drop_column('fund_listing', 'source_time')
    op.drop_column('fund_listing', 'source_url')
    op.drop_column('fund_listing', 'source_document_id')
    op.drop_table('index_family')
    # ### end Alembic commands ###
