"""create core fund schema

Revision ID: f421173b98a0
Revises: 
Create Date: 2026-08-13 00:09:50.466443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f421173b98a0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_document',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('document_type', sa.String(length=64), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('content_sha256', sa.String(length=64), nullable=True),
    sa.Column('raw_storage_path', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', 'retrieved_at', name='uq_source_document_url_retrieved_at')
    )
    op.create_index('ix_source_document_published_at', 'source_document', ['published_at'], unique=False)
    op.create_table('index_definition',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=32), nullable=False),
    sa.Column('index_code', sa.String(length=64), nullable=True),
    sa.Column('benchmark_type', sa.String(length=32), nullable=False),
    sa.Column('fx_adjustment', sa.String(length=200), nullable=True),
    sa.Column('exact_benchmark', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("benchmark_type IN ('价格指数', '净收益指数', '全收益指数', '自定义业绩基准')", name='ck_index_definition_benchmark_type'),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_index_definition_quality_status'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_index_definition_provider_code', 'index_definition', ['provider', 'index_code'], unique=False)
    op.create_table('benchmark_daily',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('index_definition_id', sa.String(length=64), nullable=False),
    sa.Column('value_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=8), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_benchmark_daily_quality_status'),
    sa.CheckConstraint('value > 0', name='ck_benchmark_daily_value_positive'),
    sa.ForeignKeyConstraint(['index_definition_id'], ['index_definition.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_definition_id', 'value_date', name='uq_benchmark_daily_index_date')
    )
    op.create_index('ix_benchmark_daily_value_date', 'benchmark_daily', ['value_date'], unique=False)
    op.create_table('fund_product',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('registration_code', sa.String(length=80), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('fund_company', sa.String(length=200), nullable=False),
    sa.Column('product_structure', sa.String(length=40), nullable=False),
    sa.Column('trading_venue', sa.String(length=20), nullable=False),
    sa.Column('investment_scopes', sa.ARRAY(sa.Text()), server_default=sa.text("'{}'::text[]"), nullable=False),
    sa.Column('tracking_method', sa.String(length=24), nullable=False),
    sa.Column('exact_benchmark_id', sa.String(length=64), nullable=True),
    sa.Column('benchmark_description', sa.Text(), nullable=False),
    sa.Column('feeder_target_product_id', sa.BigInteger(), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("((product_structure = 'ETF' AND trading_venue = '仅场内') OR (product_structure <> 'ETF' AND trading_venue = '仅场外'))", name='ck_fund_product_structure_venue'),
    sa.CheckConstraint("product_structure IN ('ETF', '普通开放式指数基金', 'ETF联接基金')", name='ck_fund_product_structure'),
    sa.CheckConstraint("tracking_method IN ('被动指数', '指数增强')", name='ck_fund_product_tracking_method'),
    sa.CheckConstraint("trading_venue IN ('仅场内', '仅场外')", name='ck_fund_product_trading_venue'),
    sa.ForeignKeyConstraint(['exact_benchmark_id'], ['index_definition.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['feeder_target_product_id'], ['fund_product.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_code')
    )
    op.create_index('ix_fund_product_benchmark', 'fund_product', ['exact_benchmark_id'], unique=False)
    op.create_index('ix_fund_product_structure_method', 'fund_product', ['product_structure', 'tracking_method'], unique=False)
    op.create_table('fund_share_class',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_product_id', sa.BigInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('share_class', sa.String(length=32), nullable=True),
    sa.Column('currency', sa.String(length=32), server_default=sa.text("'人民币'"), nullable=False),
    sa.Column('currency_form', sa.String(length=32), nullable=True),
    sa.Column('inception_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'active'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_product_id'], ['fund_product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('fund_product_id', 'share_class', 'currency', 'currency_form', name='uq_fund_share_class_identity')
    )
    op.create_index('ix_fund_share_class_product', 'fund_share_class', ['fund_product_id'], unique=False)
    op.create_table('calculated_metric',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_share_class_id', sa.BigInteger(), nullable=False),
    sa.Column('index_definition_id', sa.String(length=64), nullable=True),
    sa.Column('metric_code', sa.String(length=64), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('value_unit', sa.String(length=24), nullable=False),
    sa.Column('calculation_version', sa.String(length=64), nullable=False),
    sa.Column('calculation_inputs', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_calculated_metric_quality_status'),
    sa.CheckConstraint('period_start <= period_end', name='ck_calculated_metric_period'),
    sa.ForeignKeyConstraint(['fund_share_class_id'], ['fund_share_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['index_definition_id'], ['index_definition.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_share_class_id', 'metric_code', 'period_start', 'period_end', 'calculation_version', name='uq_calculated_metric_identity')
    )
    op.create_index('ix_calculated_metric_share_code_end', 'calculated_metric', ['fund_share_class_id', 'metric_code', 'period_end'], unique=False)
    op.create_table('fee_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_share_class_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_type', sa.String(length=32), nullable=False),
    sa.Column('rate', sa.Numeric(precision=14, scale=8), nullable=False),
    sa.Column('rate_unit', sa.String(length=16), server_default=sa.text("'percent'"), nullable=False),
    sa.Column('tier_description', sa.Text(), nullable=True),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("fee_type IN ('management', 'custody', 'sales_service', 'subscription', 'redemption', 'other')", name='ck_fee_history_type'),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_fee_history_quality_status'),
    sa.CheckConstraint('rate >= 0', name='ck_fee_history_rate_nonnegative'),
    sa.ForeignKeyConstraint(['fund_share_class_id'], ['fund_share_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fee_history_share_type_effective', 'fee_history', ['fund_share_class_id', 'fee_type', 'effective_from'], unique=False)
    op.create_table('fund_listing',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_share_class_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange', sa.String(length=16), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('listing_name', sa.String(length=100), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), server_default=sa.text("'listed'"), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("exchange IN ('上交所', '深交所')", name='ck_fund_listing_exchange'),
    sa.ForeignKeyConstraint(['fund_share_class_id'], ['fund_share_class.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange', 'ticker', name='uq_fund_listing_exchange_ticker'),
    sa.UniqueConstraint('fund_share_class_id', name='uq_fund_listing_share_class')
    )
    op.create_table('fund_scale',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_product_id', sa.BigInteger(), nullable=True),
    sa.Column('fund_share_class_id', sa.BigInteger(), nullable=True),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=24, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=32), server_default=sa.text("'人民币'"), nullable=False),
    sa.Column('amount_cny', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_fund_scale_quality_status'),
    sa.CheckConstraint('((fund_product_id IS NOT NULL)::int + (fund_share_class_id IS NOT NULL)::int) = 1', name='ck_fund_scale_single_owner'),
    sa.CheckConstraint('amount >= 0', name='ck_fund_scale_amount_nonnegative'),
    sa.ForeignKeyConstraint(['fund_product_id'], ['fund_product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['fund_share_class_id'], ['fund_share_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fund_scale_product_date', 'fund_scale', ['fund_product_id', 'report_date'], unique=False)
    op.create_index('ix_fund_scale_share_date', 'fund_scale', ['fund_share_class_id', 'report_date'], unique=False)
    op.create_table('nav_daily',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_share_class_id', sa.BigInteger(), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('unit_nav', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('accumulated_nav', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_nav_daily_quality_status'),
    sa.CheckConstraint('unit_nav > 0', name='ck_nav_daily_unit_nav_positive'),
    sa.ForeignKeyConstraint(['fund_share_class_id'], ['fund_share_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_share_class_id', 'nav_date', name='uq_nav_daily_share_date')
    )
    op.create_index('ix_nav_daily_date', 'nav_daily', ['nav_date'], unique=False)
    op.create_table('sales_limit_history',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_share_class_id', sa.BigInteger(), nullable=False),
    sa.Column('channel', sa.String(length=120), nullable=False),
    sa.Column('investor_type', sa.String(length=64), nullable=False),
    sa.Column('business_type', sa.String(length=64), nullable=False),
    sa.Column('limit_amount', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=32), server_default=sa.text("'人民币'"), nullable=False),
    sa.Column('limit_status', sa.String(length=24), nullable=False),
    sa.Column('effective_to', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_sales_limit_quality_status'),
    sa.CheckConstraint('limit_amount IS NULL OR limit_amount >= 0', name='ck_sales_limit_amount_nonnegative'),
    sa.ForeignKeyConstraint(['fund_share_class_id'], ['fund_share_class.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sales_limit_share_effective', 'sales_limit_history', ['fund_share_class_id', 'effective_from', 'effective_to'], unique=False)
    op.create_table('market_quote',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('fund_listing_id', sa.BigInteger(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('high_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('low_price', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('close_price', sa.Numeric(precision=20, scale=8), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('turnover_amount', sa.Numeric(precision=24, scale=4), nullable=True),
    sa.Column('iopv', sa.Numeric(precision=20, scale=8), nullable=True),
    sa.Column('source_document_id', sa.BigInteger(), nullable=True),
    sa.Column('source_url', sa.Text(), nullable=True),
    sa.Column('source_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('quality_status', sa.String(length=24), server_default=sa.text("'unavailable'"), nullable=False),
    sa.CheckConstraint("quality_status IN ('verified', 'delayed', 'sample', 'unavailable', 'estimated')", name='ck_market_quote_quality_status'),
    sa.CheckConstraint('close_price >= 0', name='ck_market_quote_close_nonnegative'),
    sa.ForeignKeyConstraint(['fund_listing_id'], ['fund_listing.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_document_id'], ['source_document.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_listing_id', 'trade_date', name='uq_market_quote_listing_date')
    )
    op.create_index('ix_market_quote_trade_date', 'market_quote', ['trade_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_market_quote_trade_date', table_name='market_quote')
    op.drop_table('market_quote')
    op.drop_index('ix_sales_limit_share_effective', table_name='sales_limit_history')
    op.drop_table('sales_limit_history')
    op.drop_index('ix_nav_daily_date', table_name='nav_daily')
    op.drop_table('nav_daily')
    op.drop_index('ix_fund_scale_share_date', table_name='fund_scale')
    op.drop_index('ix_fund_scale_product_date', table_name='fund_scale')
    op.drop_table('fund_scale')
    op.drop_table('fund_listing')
    op.drop_index('ix_fee_history_share_type_effective', table_name='fee_history')
    op.drop_table('fee_history')
    op.drop_index('ix_calculated_metric_share_code_end', table_name='calculated_metric')
    op.drop_table('calculated_metric')
    op.drop_index('ix_fund_share_class_product', table_name='fund_share_class')
    op.drop_table('fund_share_class')
    op.drop_index('ix_fund_product_structure_method', table_name='fund_product')
    op.drop_index('ix_fund_product_benchmark', table_name='fund_product')
    op.drop_table('fund_product')
    op.drop_index('ix_benchmark_daily_value_date', table_name='benchmark_daily')
    op.drop_table('benchmark_daily')
    op.drop_index('ix_index_definition_provider_code', table_name='index_definition')
    op.drop_table('index_definition')
    op.drop_index('ix_source_document_published_at', table_name='source_document')
    op.drop_table('source_document')
    # ### end Alembic commands ###
